name: Build and Push Microservices

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: secrets.DOCKERHUB_USERNAME

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push login service
        run: |
          docker build -t $DOCKERHUB_USERNAME/login-service ./login
          docker push $DOCKERHUB_USERNAME/login-service

      - name: Build and push payment service
        run: |
          docker build -t $DOCKERHUB_USERNAME/payment-service ./payment
          docker push $DOCKERHUB_USERNAME/payment-service

      - name: Build and push checkout service
        run: |
          docker build -t $DOCKERHUB_USERNAME/checkout-service ./checkout
          docker push $DOCKERHUB_USERNAME/checkout-service

          
