name: ArgoCD App

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GITOPS_REPO: https://github.com/SharmilaNagarajan1/argocd-deploy.git

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push login service
        uses: docker/build-push-action@v4
        with:
          context: ./login
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/login-service:${{ github.sha }}

      - name: Build and push payment service
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.sha }}

      - name: Build and push checkout service
        uses: docker/build-push-action@v4
        with:
          context: ./checkout
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:${{ github.sha }}

    

   

          
