name: ArgoCD App

on:
  push:
    branches:
      - main

env:
  
  GITOPS_REPO: SharmilaNagarajan1/argocd-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push login service
        uses: docker/build-push-action@v4
        with:
          context: ./login
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/login-service:${{ github.sha }}

      - name: Build and push payment service
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:${{ github.sha }}

      - name: Build and push checkout service
        uses: docker/build-push-action@v4
        with:
          context: ./checkout
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:latest
             ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:${{ github.sha }}

      - name: Clone GitOPs repo and update manifest
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

          git clone https://${{ secrets.GITOPS_PAT}}@${{ env.GITOPS_REPO }} 
          cd argocd-deploy
   
          sed -i "s|image: .*login-service.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest|" login-deployment.yaml
          sed -i "s|image: .*payment-service.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest|" payment-deployment.yaml
          sed -i "s|image: .*checkout-service.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:latest|" checkout-deployment.yaml

          git add .
          git commit -m "CI: Update image tags for login, payment, checkout"
          git push 

          
